# Generated by Django 5.2.4 on 2025-08-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('cedula', models.CharField(max_length=45, unique=True)),
                ('cargo', models.CharField(max_length=80)),
                ('fecha_ingreso', models.DateField()),
                ('departamento', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=45)),
                ('estado_civil', models.CharField(max_length=45)),
            ],
        ),
    ]
