# Generated by Django 5.2.4 on 2025-08-03 23:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('obligatorio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_presentacion', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='media/documentos/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'doc', 'docx'])])),
                ('estado', models.CharField(max_length=45)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.perfilfuncionario')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento')),
            ],
        ),
    ]
