# Generated by Django 5.2.4 on 2025-08-19 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='fecha',
            new_name='fecha_evaluacion',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='tipo_evaluacion',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='acta_evaluacion',
            field=models.FileField(blank=True, null=True, upload_to='evaluaciones/actas/'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='id_funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='funcionarios.perfilfuncionario', verbose_name='Funcionario'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='periodo_evaluacion',
            field=models.CharField(choices=[('S1', 'Primer semestre'), ('S2', 'Segundo semestre')], default='S1', max_length=2),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tipo_personal',
            field=models.CharField(choices=[('CONTRATADO', 'Contratado'), ('PERMANENTE', 'Permanente'), ('COMISIONADO', 'Comisionado')], default='CONTRATADO', max_length=20),
        ),
    ]
