# Generated by Django 5.2.4 on 2025-08-08 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventoslaborales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventolaboral',
            old_name='funcionario',
            new_name='id_funcionario',
        ),
        migrations.RemoveField(
            model_name='eventolaboral',
            name='resolucion',
        ),
        migrations.AddField(
            model_name='eventolaboral',
            name='beneficio',
            field=models.CharField(blank=True, choices=[('bonos', 'Bonos'), ('subsidios', 'Subsidios'), ('becas', 'Becas')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventolaboral',
            name='url_resolucion_evento',
            field=models.FileField(blank=True, null=True, upload_to='resoluciones/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='eventolaboral',
            name='tipo_evento',
            field=models.CharField(choices=[('vacaciones', 'Vacaciones'), ('sanciones', 'Sanciones'), ('traslados', 'Traslados'), ('permisos', 'Permisos'), ('beneficios', 'Beneficios')], max_length=100),
        ),
    ]
