# Generated by Django 5.2.4 on 2025-08-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventoslaborales', '0002_rename_funcionario_eventolaboral_id_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventolaboral',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
